### ISSUE TITLE
Calls to log trigger basicConfig

### ISSUE THREAD

**Issue by DavideCanton** [pytest-dev/pytest-nunit#68]
This plugin invokes some logging methods from its pytest_configure method through the creation of a `NunitXML` object.

The problem is that in scenarios where I have no handler added to the logger (because I don't need it in test executions), the calls from the plugin trigger a basicConfig and then all the log is printed in the test run.

To avoid the problem, I added in my own configure hook a `NullHandler` to the root logger, maybe it's something this library can do to avoid the problem?

**Comment by Uil2liv** [comment]
Got same problem here.
replacing the following line 
https://github.com/pytest-dev/pytest-nunit/blob/0f77d530feba1236ffe2da8eba3fbd21993c7fce/pytest_nunit/plugin.py#L283
by
` log.debug("Attach on criteria : {0}".format(attach_on))`
seem to prevent the problem : it then use its own logger instead of trying to use the root one.
